### PR TITLE
add Actions workflow to push to Replicate

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a GitHub Actions workflow for pushing the model to Replicate. The workflow is triggered manually in the Actions tab.

- [x] Create a token for the @stability-ai org on Replicate
- [x] Add that token to this repo's secrets as `REPLICATE_API_TOKEN`
- [x] Test the workflow on a copy of this repo to confirm that it works (because [`workflow_dispatch` can only be used on a repo's default branch](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually))
- [ ] Get review from the team
- [ ] Merge this PR 🤞

### CODE REVIEW

**Comment by zeke** [comment]
Doh! Can't test this from a pull request.

> To trigger the `workflow_dispatch` event, your workflow must be in the default branch.

**Comment by zeke** [comment]
This is ready to go. I tested it by creating a duplicate of this repo and triggering the workflow from the main branch.

✅ `REPLICATE_API_TOKEN` is set as a repository secret.

**Comment by zeke** [comment]
This is ready to go!

**Comment by zeke** [comment]
Update after an internal team discussion: Given that this is a particularly popular and high-traffic model, it must be released with a high degree of care and attention, so it's not the best candidate model to be a guinea pig for this new Actions workflow. We'll instead test it out on some lower stakes models, and eventually publish a generic Cog Action for broader use.

**Comment by chigozienri** [comment]
@zeke Does a generic Cog Action now exist?

**Comment by zeke** [comment]
@chigozienri yep! https://github.com/replicate/setup-cog

**Pull request closed without merging**
