### PR TITLE
Add new schedulers and negative prompt

### PR DESCRIPTION
**Pull request by vshashkov**
# What is this?

1. In this PR I've upgraded the `diffusers` library to the latest one - [v0.7.1](https://github.com/huggingface/diffusers/releases/tag/v0.7.1)
2. Added support for new param: `negative_prompt`
3. Added support for new schedulers: `EulerAncestralDiscreteScheduler`, `EulerDiscreteScheduler`

# Why?
With this PR I want to improve the current cog version for the model, so other community members can start using the latest custom schedulers and set up negative prompt.

# How did you test to ensure no regressions?
I've used [brev console](https://console.brev.dev/) for testing it.
Screenshot 2022-11-04 at 21 31 39

# Testing results:
Below are my testing results with different schedulers with default settings and other custom input:

**prompt:**
_Ragdoll cat king wearing a golden crown, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, Tomasz Alen Kopera, Peter Mohrbacher, donato giancola, Joseph Christian Leyendecker, WLOP, Boris Vallejo_

**seed:** _789_

Screenshot 2022-11-04 at 21 25 25

and with **negative prompt** _yellow color, cat, nose_ with `K_EULER_ANCESTRAL`:
Screenshot 2022-11-04 at 21 35 55

### CODE REVIEW

**Comment by bfirsh** [comment]
Amazing, thank you for the contribution.

I have got this running here: https://replicate.com/bfirsh/stable-diffusion-test/versions/925f439d32dac43d05c9c3b6eb81de6ba9d04d96b441ad56e359708adfd8de3e

I have compared output with same seed from K-LMS and PNDM. and looks like it's the same.

However, for DDIM, looks like it's producing weird output.

Current version: https://replicate.com/p/ffuqqva32vg4xg34wwz6iddzrm
Your version: https://replicate.com/p/txkysa3ktjbptoueyquscsgsqy

What is the change to `from_config()` on the scheduler doing, do you know? Maybe it's using different params?

**Comment by vshashkov** [comment]
Thank you @bfirsh!

1. Regarding `from_config()`, from my understanding it reads the defaults from the model's default schedulers config file and selects params that are required for the current scheduler. I found this usage in [diffusers library](https://github.com/huggingface/diffusers).
Screenshot 2022-11-05 at 17 32 22
Screenshot 2022-11-05 at 17 31 51

2. Regarding the DDIM on the latest version. It's too weird. As it gives great results in my test environment.
Screenshot 2022-11-05 at 17 43 46
Screenshot 2022-11-05 at 17 45 15

And running this on this env:
Screenshot 2022-11-05 at 17 48 46

**Comment by vshashkov** [comment]
> This looks like an awesome change!
> 
> I wonder what it would take to get it over the line.
> 
> Looks like a lot of folks are interested in the negative prompt input (#27) -- would it be worth splitting that out into a separate PR that might not be blocked by this `DDIM` discrepancy?

Opened a separate PR with only negative prompt support here: https://github.com/replicate/cog-stable-diffusion/pull/49

**Comment by vshashkov** [comment]
I think this PR is not relevant anymore. Part of it (w/ new diffusers was also merged [here](https://replicate.com/stability-ai/stable-diffusion/versions/27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478)).

**Pull request closed without merging**
