### PR TITLE
share config between predictor and script(s)

### PR DESCRIPTION
**Pull request by zeke**
This PR creates a shareable config, so you only have to change it in one place.

This is untested. Am I doing it right?

cc @replicate/models

### CODE REVIEW

**Comment by daanelson** [comment]
Python's a bit finicky about relative imports from `.py` files in different folders; right now this'll fail if you run `cog run scripts/download_weights` like so:

`Running 'script/download-weights' in Docker with the current directory mounted as a volume...
Traceback (most recent call last):
  File "/src/script/download-weights", line 10, in <module>
    from ..config import MODEL_ID, MODEL_CACHE, SAFETY_MODEL_ID
ImportError: attempted relative import with no known parent package`

Alternate options that should work:
- keep the config in `download-weights`, rename to `download_weights` (because snake case) and then import from there in `predict.py`
- add a `config.yaml` to `script` and load from there in both places. don't like this b/c one yaml config should be enough, perhaps there's a way to generate a `config.yaml` from the `run:` section in `cog.yaml`.

**Comment by zeke** [comment]
> * keep the config in `download-weights`, rename to `download_weights` (because snake case) and then import from there in `predict.py`

I did this but the opposite: put the config in predict.py and import it from the script. Does that seem sensible? https://github.com/replicate/cog-stable-diffusion/pull/73/commits/e291fd4c81c6e407fa3e8b43b612c087d8e09dec

**Comment by zeke** [comment]
This is ready for another look.

**Comment by zeke** [comment]
I just tried to test this but ran into an issue: https://github.com/replicate/cog-stable-diffusion/issues/74 (which is not specific to this branch; also happens on the main branch)

**Comment by zeke** [comment]
Finally got this working on Codepsaces, both with the default waits and `prompthero/openjourney-v2`.

This is ready for a final look!

**Comment by daanelson** [comment]
looks great! nice and DRY.

**Review by daanelson — APPROVED** [review]

**Pull request merged**
